# Generated by Django 6.1 on 2026-08-22 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('cost_index', models.CharField(blank=True, default='$$', max_length=20)),
                ('popularity', models.CharField(blank=True, default='High', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, default='Sightseeing', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration', models.CharField(blank=True, default='2 hours', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='travel.city')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['name'],
                'unique_together': {('name', 'city')},
            },
        ),
    ]
