# Generated by Django 6.1 on 2026-08-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop',
            old_name='departure_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='stop',
            old_name='arrival_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stop',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
