# Generated by Django 6.1 on 2026-08-22 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_rename_departure_date_stop_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripactivity',
            name='trip',
        ),
        migrations.AddField(
            model_name='activity',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration_hours',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(default='Sightseeing', max_length=255),
        ),
        migrations.AddField(
            model_name='tripactivity',
            name='cost_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tripactivity',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripactivity',
            name='stop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trip_activities', to='trips.stop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tripactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_activities', to='trips.activity'),
        ),
    ]
